### PR TITLE
footerView notifyItemInserted fix

### PR DESCRIPTION
**Pull request by dvasko**
find position of footer before adding footerView or footerViewId

### CODE REVIEW

**Comment by zplesac** [comment]
Hi @dvasko - could you explain in more details what are you trying to achieve with the proposed changes? You are actually only extracting the result of _getItemCount()_ method to a variable, and calling _ notifyItemInserted()_ method with this variable as a input parameter. Basically, the behaviour remains the same as before with proposed changes.

**Comment by dvasko** [comment]
if you call getItemCount() before 
```
this.footerView = footerView;
```
you will get right position opposite to if you call getItemCount() after that same line.

example
your list has 0 items and you add 1 header and 1 footer
with your implementation getItemCount would return 2 and you would call notifyItemInserted(2) which is wrong index of footer, footer is on index 1.
So my fix was to extract count before adding view reference so getItemCount would return 1 same thing that you did in
```
    public void add(E item) {
        int position = items.size();
        items.add(item);
        notifyItemInserted(position);
    }
```

**Comment by zplesac** [comment]
You're right! But also, you're implementation will notify at wrong position if you call addFooter twice in a row - the correct implementation should be:

```
public void addFooter(@LayoutRes int footerViewId) {
        int position = getCollectionCount() + (hasHeader() ? 1 : 0);
        this.footerViewId = footerViewId;
        notifyItemInserted(position);
    }
```

_getCollectionCount()_ will return size of the items in adapter + it will add 1 or 0, depending on if the adapter has/doesn't has header. 

With this change, if we go back to your original example:
* if collection is empty and we add header and footer, the notifyItemInserted() will be called with position 1
* if collection is empty and we add footer, the notifyItemInserted() will be called with position 0
* if collection has 3 items and header and footer, the notifyItemInserted() will be called with position 3
* if collection has 3 items and only footer, the notifyItemInserted() will be called with position 2

**Comment by dvasko** [comment]
definitely it better. 

> * if collection has 3 items and header and footer, the notifyItemInserted() will be called with position 3 -> **4**
* if collection has 3 items and only footer, the notifyItemInserted() will be called with position 2 -> **3**

Some note about calling multiple times addHeader or addFooter.
(Debatable) Currently library doesn't support adding multiple headers or footer (like ListView) so i would rather see thrown error with description when you try calling addHeader or addFooter for the second time. That way user of library know that calling multiple time addHeader won't produce desirable behavior (2 headers on top of the RecyclerView)

**Comment by zplesac** [comment]
@dvasko I agree, it has a little bit undefined behaviour. I'll merge this PR, close it and open a new issue for defining that behaviour.

Thanks for an awesome bug fix.

**Pull request merged**
